version: "3"

services:
  app:
    build: ./stocks_products/
    restart: always
    env_file:
      - ./env/.app_env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - staticfiles:/app/static
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./env/.postgres_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./database:/var/lib/postgresql/data
  ngnix:
    image: nginx:alpine
    restart: always
    volumes:
      - staticfiles:/home/staticfiles
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  staticfiles: